// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Flee: typeof import('./src/components/Flee.vue')['default']
    Flee3D: typeof import('./src/components/Flee3D.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
  }
}

export { }
